export const DEFAULT_PACKING_ITEMS = [
  { category: "Food", name: "Curd", qty: "3", note: "" },
  { category: "Food", name: "Milk", qty: "", note: "" },
  { category: "Food", name: "Water", qty: "5 litres", note: "" },
  { category: "Food", name: "Eggs", qty: "30 + 10", note: "" },
  { category: "Food", name: "Mushroom", qty: "", note: "" },
  { category: "Food", name: "Nutella", qty: "", note: "" },
  { category: "Food", name: "Pindakaas", qty: "", note: "" },
  { category: "Food", name: "Kids curd", qty: "", note: "" },
  { category: "Food", name: "Bread", qty: "3", note: "" },
  { category: "Food", name: "Onion", qty: "", note: "" },
  { category: "Food", name: "Rice", qty: "3 kg", note: "" },
  { category: "Food", name: "Banana", qty: "", note: "" },
  { category: "Food", name: "Orange", qty: "", note: "" },
  { category: "Kitchen", name: "Cooling box", qty: "", note: "" },
  { category: "Kitchen", name: "Plates", qty: "", note: "" },
  { category: "Kitchen", name: "Cups", qty: "", note: "" },
  { category: "Kitchen", name: "Knife", qty: "", note: "" },
  { category: "Kitchen", name: "Chopping board", qty: "", note: "" },
  { category: "Kitchen", name: "Dish drainer / rack", qty: "", note: "Confirm wording" },
  { category: "Kitchen", name: "Sponge", qty: "", note: "" },
  { category: "Kitchen", name: "House cleaning brush", qty: "", note: "" },
  { category: "Kids", name: "Toys", qty: "", note: "" },
  { category: "Health", name: "Medicine", qty: "", note: "" },
  { category: "Health", name: "Tablets", qty: "", note: "" },
  { category: "Health", name: "Bandage", qty: "", note: "" },
  { category: "Health", name: "Cotton", qty: "", note: "" },
  { category: "Health", name: "Nasal spray", qty: "", note: "" },
  { category: "Health", name: "Mosquito repellent", qty: "", note: "" },
  { category: "Clothing", name: "Umbrella", qty: "", note: "" },
  { category: "Clothing", name: "Rain cover / raincoat", qty: "", note: "" },
  { category: "Clothing", name: "Hairdryer", qty: "", note: "" },
  { category: "Clothing", name: "Dresses / clothes", qty: "", note: "" },
  { category: "Clothing", name: "Towels", qty: "", note: "" },
  { category: "Clothing", name: "Swimwear", qty: "", note: "" },
  { category: "Clothing", name: "Swimming gear", qty: "", note: "" },
  { category: "Clothing", name: "Bags for old clothes", qty: "", note: "" },
  { category: "Clothing", name: "Socks", qty: "", note: "" },
  { category: "Clothing", name: "Jackets", qty: "", note: "" },
  { category: "Clothing", name: "Head cover", qty: "", note: "" },
  { category: "Clothing", name: "Head cover (Wintersport)", qty: "", note: "Purchase item" },
  { category: "Clothing", name: "Shoes", qty: "", note: "" },
  { category: "Clothing", name: "Crocs", qty: "", note: "" },
  { category: "Hygiene", name: "Wet tissue", qty: "", note: "" },
  { category: "Hygiene", name: "Wet toilet paper", qty: "", note: "" },
  { category: "Hygiene", name: "Bath items", qty: "", note: "" },
  { category: "Hygiene", name: "Lotion", qty: "", note: "" },
  { category: "Camping Gear", name: "Electric cables", qty: "", note: "" },
  { category: "Camping Gear", name: "Pump", qty: "", note: "" },
  { category: "Camping Gear", name: "Hammer", qty: "", note: "" },
  { category: "Camping Gear", name: "Gloves", qty: "", note: "" },
  { category: "Camping Gear", name: "Toilet box", qty: "", note: "" },
  { category: "Camping Gear", name: "Toilet paper", qty: "", note: "" },
  { category: "Camping Gear", name: "Dustbin cover", qty: "", note: "" },
  { category: "Camping Gear", name: "Inside mat", qty: "", note: "" },
  { category: "Camping Gear", name: "Outside mat", qty: "", note: "" },
  { category: "Sleeping", name: "Bed sheets", qty: "", note: "" },
  { category: "Sleeping", name: "Pillows", qty: "", note: "" },
  { category: "Furniture", name: "Chairs", qty: "", note: "" },
  { category: "Furniture", name: "Dressing case / basket", qty: "", note: "Confirm wording" },
  { category: "Furniture", name: "Folding table", qty: "", note: "" },
  { category: "Electronics", name: "Bluetooth speaker", qty: "", note: "" },
  { category: "Electronics", name: "Lights", qty: "", note: "" },
  { category: "Electronics", name: "Heater", qty: "", note: "" }
];
